upgrade theano 1.0
ryanjulian/rllab pull request #57
Opened 2018-05-09 16:50 UTC by cjcchen

theano has been upgraded to 1.0

2018-05-15 22:30 UTC, ryanjulian commented
@cjcchen can you confirm that this doesn't break anything?

2018-05-15 22:30 UTC, ryanjulian commented
fixes #17

2018-05-16 16:27 UTC, cjcchen commented
I have checked it from the website and run the all the examples in the example folder. It seems only the Lasagne library has to be updated.

2018-05-16 16:53 UTC, cjcchen commented
In the official document,  one change is related to our library "Changed grad() method to L_op() in ops that need the outputs to compute gradient". But it seems the grad function in rllab works fine after I  upgraded the theano to verioin 1.0.

2018-05-16 17:12 UTC, eric-heiden submitted a review, later dismissed

2018-05-16 17:24 UTC, ryanjulian requested changes
We need to pin versions for large dependencies (really, all dependencies, but it is most important for large ones).

2018-05-16 17:24 UTC, ryanjulian commented on environment.yml
> +    - mkl-service
please pin to a specific version

2018-05-16 17:24 UTC, ryanjulian commented on environment.yml
> +        - git+https://github.com/Theano/Theano.git#egg=Theano
please pin to a specific version or git hash/release tag.

http://deeplearning.net/software/theano_versions/dev/install_ubuntu.html states "The latest stable version of Theano is 1.0.1 (tagged with rel-1.0.1)."

2018-05-16 17:24 UTC, ryanjulian commented on environment.yml
> +        - git+https://github.com/Lasagne/Lasagne.git#egg=Lasagne
please pin to a specific version or git hash/release tag

2018-05-17 02:03 UTC, closed without merging