Added async support to 3D plotting in TensorFlow
ryanjulian/rllab pull request #71
Opened 2018-05-21 23:26 UTC by jonashen

2018-05-24 02:00 UTC, gonzaiva commented
Sorry about closing the request, I was cleaning some of my branches and this request closed for some reason. I restored it back. Sorry for the inconvenience.

2018-05-25 20:56 UTC, CatherineSue approved these changes

2018-05-29 18:25 UTC, ryanjulian requested changes

2018-05-29 18:25 UTC, ryanjulian commented on sandbox/rocky/tf/plotter/__init__.py
> +from .plotter import *
PEP8: no relative imports

2018-05-29 18:25 UTC, ryanjulian commented on sandbox/rocky/tf/plotter/plotter.py
> +from rllab.sampler.utils import rollout
PEP8: import grouping

2018-05-29 18:25 UTC, ryanjulian commented on sandbox/rocky/tf/plotter/plotter.py
> +                        # env.start_viewer()
please don't commit commented-out code

2018-05-29 18:25 UTC, ryanjulian commented on sandbox/rocky/tf/algos/batch_polopt.py
>  from rllab.sampler.utils import rollout
PEP8: import grouping

Note: we put rllab. and sandbox. packages in separate groups.

2018-05-29 18:25 UTC, ryanjulian commented on sandbox/rocky/tf/algos/batch_polopt.py
> +            # rollout(self.env, self.policy, animated=True, max_path_length=self.max_path_length)
please don't commit commented-out code.

is there any way we can do this in `plotter.init_plot()` to make the API simpler?

2018-06-07 00:12 UTC, closed without merging